title: Figo Payments - Arquitetura
description: Documentação Técnica da Arquitetura Cloud AWS
theme: jekyll-theme-cayman

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  parse_span_html: true
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Plugins
plugins:
- jekyll-relative-links

# Relative links settings
relative_links:
  enabled: true
  collections: true

# Exclude files
exclude:
- .nojekyll
- node_modules
- vendor
- DEPLOY-GITHUB-PAGES.md
